" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" set encoding
set encoding=utf-8

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

" Turn on syntax highlight
syntax on

" For plugins to load correctly
filetype plugin indent on

" Show line numbers
set number

" Show file stats show lines and columns bottom right
set ruler

" Blink cursor on error instead of beeping (grr)
set visualbell

"Convert tabs to space
set expandtab

"Move between buffers without saving
set hidden

"Highlig current line
set cursorline

"Highling current column
set cursorcolumn

"Set relative line numbers
set relativenumber

"Search down into subfolders
"Provides tab-completion for all file-related tasks
set path +=**

"Display all matching files when we tab complete
set wildmenu

"Display all matching files when we tab complete
set wildmode=longest,list,full

"Use system clipboard if 'unnamedplus' doesn´t work, try 'unnamed'
set clipboard+=unnamedplus

"Turn on backup option
set backup

"Backup files in dir ~/.vimbackups
set backupdir=~/.vimbackups

"Make backup before overwriting the current buffer
set writebackup

"Overwrite the original backup file
set backupcopy=yes

"Spell checker
setlocal spell spelllang=en_us

"set mouse to enable
"set mouse=a

"Backup files with ORIGINALFILENAME-YYYYMMDD-HHMMSS.vimbackup
au BufWritePre * let &bex = '-' . strftime("%Y%m%d-%H%M%S") . '.vimbackup'

"Add yaml stuffs
au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml "foldmethod=indent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

"Add plugins
so ~/.vim/plugins.vim

"Add plugins config
so ~/.vim/plugins-config.vim

" Set the dracula theme after plugins have been loaded
colorscheme dracula

"custom for each format python, sh, terraform
if has("autocmd")
 augroup python
  au!
  autocmd BufNewFile,BufReadPre,FileReadPre        *.py set tabstop=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.py set softtabstop=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.py set shiftwidth=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.py set expandtab
  autocmd BufNewFile,BufReadPre,FileReadPre        *.py set autoindent
  autocmd WinEnter,VimEnter *.py :call rainbow#enable()
  autocmd FileType python map <buffer> <F5> :exec '!clear && python3 -m ipdb' shellescape(@%, 1)<cr>
  autocmd FileType python map <buffer> <F6> :exec '!clear && python3' shellescape(@%, 1)<cr>
  autocmd FileType python map <buffer> <F7> :exec '!clear && python3 -m pytest . '<cr>
  autocmd FileType python map <buffer> <F8> :exec '!clear && tox -e unit '<cr>
  autocmd FileType python map <buffer> <F4> :exec '!clear && pudb' shellescape(@%, 1)<cr>
 augroup END
endif

if has("autocmd")
 augroup sh
  au!
  autocmd BufNewFile,BufReadPre,FileReadPre        *.sh set tabstop=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.sh set softtabstop=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.sh set shiftwidth=4
  autocmd BufNewFile,BufReadPre,FileReadPre        *.sh set expandtab
  autocmd BufNewFile,BufReadPre,FileReadPre        *.sh set autoindent
  autocmd WinEnter,VimEnter *.sh :call rainbow#enable()
  autocmd FileType sh map <buffer> <F5> :exec '!clear && bash -xv ' shellescape(@%, 1)<cr>
  autocmd FileType sh map <buffer> <F6> :exec '!clear && bash ' shellescape(@%, 1)<cr>
 augroup END
endif

if has("autocmd")
 augroup terraform
  au!
  autocmd BufNewFile,BufReadPre,FileReadPre        *.tf set tabstop=2
  autocmd BufNewFile,BufReadPre,FileReadPre        *.tf set softtabstop=2
  autocmd BufNewFile,BufReadPre,FileReadPre        *.tf set shiftwidth=2
  autocmd BufNewFile,BufReadPre,FileReadPre        *.tf set expandtab
  autocmd BufNewFile,BufReadPre,FileReadPre        *.tf set autoindent
  autocmd WinEnter,VimEnter *.tf :call rainbow#enable()
  autocmd FileType terraform  map <buffer> <F5> :exec '!clear && terraform fmt -check -diff' shellescape(@%, 1)<cr>
  autocmd FileType terraform  map <buffer> <F6> :exec '!clear && terraform fmt' shellescape(@%, 1)<cr>
  autocmd FileType terraform  map <buffer> <F7> :exec '!clear && terraform init && terraform validate' <cr>
  autocmd FileType terraform  map <buffer> <F8> :exec '!clear && terraform plan' <cr>
 augroup END
endif
